[workspace]
resolver = "3"
members = [
    "core_engine",
    "management_api",
    "cli_client",
    "gui_client",
    "shared_utils",
    "shared_utils/fuzz",
    "coentro_ipc",
    "coentro_helper",
    "coentro_client",
    "coentro_server_helper",
    "coentroctl"
]
